class Receipt {
  String name;
  String description;
  String imageAsset;
  List<String> ingredients;
  List<String> howToMake;

  Receipt({
    required this.name,
    required this.description,
    required this.imageAsset,
    required this.ingredients,
    required this.howToMake,
  });
}

var receiptList = [
  Receipt(
    name: 'Manggut Nila Asap Kemangi',
    description:
        'Mangut Nila Asap Kemangi adalah hidangan ikan nila asap dengan bumbu santan dan daun kemangi. Resep ini sederhana namun menghasilkan rasa yang gurih. ',
    imageAsset: 'images/manggut_nila_asap_kemangi.jpg',
    ingredients: [
      '3 buah nila asap',
      '5 siung bawang merah',
      '1 sachet santan instan',
      '3 siung bawang putih',
      '3 butir kemiri',
      '1 sdt kunyit bubuk',
      '1 ruas jahe',
      '2 batang serai digeprek',
      '3 helai daun salam',
      '3 lembar daun jeruk',
      '1 ruas lengkuas',
      'Gula merah sisir (saya ganti gula pasir)',
      'Garam',
      '1 genggam daun kemangi',
    ],
    howToMake: [
      '1. Tumis bumbu halus (bawang merah, bawang putih, kemiri, jahe, kunyit bubuk) dan tambahkan bumbu c mplung (lengkuas, daun salam, daun jeruk, sereh). Tumis sampai harum dan matang.',
      '2. Tambahkan air, beri bumbu (gula, garam dan kaldu bubuk). Koreksi rasa. Jika rasa sdh pas tambahkan santan dan masak sampai santan mendidih.',
      '3. Tambahkan ikan nila asapnya dan masak sebentar sampai bumbu meresap di ikan. Terakhir sebelum dimatikan apinya tambahkan daun kemangi. Matikan api. Siap disajikan selagi hangat.',
    ],
  ),
  Receipt(
    name: 'Sosis Solo',
    description:
        'Makanan khas dari kota #solo provinsi Jawa Tengah yang terbuat dari daging sapi atau ayam. Konon kabarnya Sosis Solo ada pada jaman Kanjeng Sultan Pakubowono X.',
    imageAsset: 'images/sosis_solo.jpg',
    ingredients: [
      '500 gr daging dada ayam direbus setelah itu disuruh atau di chopper',
      '5 siung Bawang merah',
      '3 siung Bawang putih',
      '1 sdm ketumbar bubuk',
      '1 batang sereh nemarkan',
      '3-4 sdm gula pasir',
      '1/2 sdt garam',
      '1 sdt lada',
      '2 lembar daun salam',
      '30 ml atau ½ bks santan kara kecil',
      '250 gr terigu',
      '500-600 ml air',
      '1 butir telur',
      '1 sdm tapioka',
      'Secukupnya garam',
      '1 butir telur',
      '2 sdm tepung beras',
      'Secukupnya air',
      'Minyak goreng untuk menumis dan menggoreng',
    ],
    howToMake: [
      '1. Memasak Isian: Haluskan Bawang merah dan putih lalu tumis dengan daun salam, sereh, lada dan ketumbar hingga harum. Kemudian masukan ayam yg sdh disuir halus aduk rata tambahkan santan, gula, garam, penyedap rasa dan sedikit air lalu masak hingga mengering. Koreksi rasa lalu sisihkan',
      '2. Memasak Kulit: Campurkan semua bahan lalu tuangkan air sedikit demi sedikit agar tidak ada adonan yg menggumpal tambahkan telur dan 1 sdm minyak goreng lalu aduk hingga merata',
      '3. Panaskan wajan anti lengket utk mencetak kulit. Tuangkan 1 sendok sayur adonan ratakan di wajan lalu tunggu hingga pinggiran kulit mengelupas. Lakukan langkah ini hingga adonannya habis.',
      '4. Ambil 1 lembar kulit, lalu berikan kurleb 1 sdm atau secukupnya isian kemudian lipat keatas sisi bawahnya dan lipat sisi kiri dan kanannya kemudian gulung kedepan hingga membentuk seperti risol. Lakukanlangkah ini hingga kulit dan isian habis.',
      '5. Campurkan seluruh bahan pelapis, aduk hingga tercampur rata. Sebelum digoreng sosis dicelupkan terlebih dahulu kedalam adonan bahan pelapis.',
      '6. Panaskan minyak goreng di wajan untuk menggoreng dengan api sedang. Apabila sudah panas goreng sosis.',
      '7. Goreng semua sosis solonya hingga matang berwarna kuning kecoklatan. Setelah itu tiriskan',
    ],
  ),
  Receipt(
    name: 'Telur Balado',
    description:
        'Mangut Nila Asap Kemangi adalah hidangan ikan nila asap dengan bumbu santan dan daun kemangi. Resep ini sederhana namun menghasilkan rasa yang gurih.',
    imageAsset: 'images/telur_balado.jpg',
    ingredients: [
      '1 kg telur',
      '2 ons cabe keriting',
      '11 buah caber rawit',
      '5 siung bamer',
      '3 siung baput',
      '2 buah tomat',
      '1 lembar daun salah',
      '1 batang sereh',
      '1 lembar daun kunyit',
      'Secukupnya minyak goreng',
      'Secukupnya gula garam',
    ],
    howToMake: [
      '1. Rebus telur sekitar 10 menit kemudian kupas',
      '2. Telur Balado langkah memasak 1 foto',
      '3. Haluskan semua bumbu. Bole pakai terasi sedikit kalau suka.',
      '4. Telur Balado langkah memasak 2 foto',
      '5. Telur Balado langkah memasak 2 foto',
      '6. Tumis bumbu halus sampai wangi. Masukan gula garam dan koreksi rasa. Terakhir masukkan telur yang sudah dikupas.',
      '7. Telur Balado langkah memasak 3 foto',
    ],
  ),
  Receipt(
    name: 'Tahu Kukus Bawang Putih',
    description:
        'Tahu Kukus Bawang Putih adalah hidangan tahu yang dimasak dengan cara dikukus dan disiram dengan saus bawang putih dan ebi.',
    imageAsset: 'images/tahu_kukus_bawang_putih.jpg',
    ingredients: [
      '2 buah tahu putih ukuran sedang, potong-potong tipis, kukus 15 menit',
      '2 siung bawang putih cincang',
      '1 sdm minyak goreng',
      '1 sdm ebi cincang',
      '1 sdm kecap asin',
      '1,5 sdm kecap manis',
      '1 sdt saus tiram',
      '1/2 sdt gula pasir',
      '1/4 buah jeruk nipis, ambil airnya',
      'secukupnya Air',
      'secukupnya Daun bawang iris',
    ],
    howToMake: [
      '1. Tumis bawang putih sampai harum, lalu tambahkan ebi cincang, tumis hingga kecoklatan.',
      '2. Tambahkan kecap manis, saus tiram, gula pasir, air perasan jeruk nipis dan air matang secukupnya. Masak hingga sedikit mengental. Koreksi rasa, matikan api.',
      '3. Tata tahu diatas piring saji.',
      '4. Siram dengan saus, beri taburan daun bawang. Sajikan hangat.',
    ],
  ),
  Receipt(
    name: 'Acar Kuning ~ Buncis Wortel Timun',
    description: 'Hidangan sayuran yang dimasak dengan bumbu asam dan pedas.',
    imageAsset: 'images/acar_kuning.jpg',
    ingredients: [
      '3 buah timun/315gr',
      '3 buah Wortel kecil /120gr',
      '100 gr buncis',
      '2 sdm air asam jawa',
      'Secukupnya garam dan gula',
      'Secukupnya air',
      '5 siung bwg merah',
      '3 siung bwg putih',
      '2 butir kemiri',
      '3 cabe merah keriting',
      '1 ruas jari kunyit',
    ],
    howToMake: [
      '1. Potong memanjang buncis, wortel, dan timun (untuk timun dibuang bijinya) Haluskan cabe, bawang, kemiri, dan kunyit. Larutkan juga asam Jawa dengan sedikiit air. Sisihkan.',
      '2. Panaskan secukupnya minyak goreng, tumis bumbu halus sampe harum. Masukan wortel dan buncis, aduk masak sampai agak layu. Tambahkan secukupnya air.',
      '3. Tambahkan garam, gula, dan air asem. Lalu masukan timun, aduk rata, test rasa.',
      '4. Masak sebentar aja supaya timun ga lembek. Matikan api.',
    ],
  ),
  Receipt(
    name: 'Ayam Jamur Kuping',
    description:
        'Ayam Jamur Kuping adalah hidangan yang terbuat dari fillet paha ayam dan jamur kuping, yang ditumis dengan bumbu seperti bawang putih, bawang merah, cabai merah, tomat, dan kecap manis. ',
    imageAsset: 'images/ayam_jamur.jpg',
    ingredients: [
      '250 gr ayam fillet bagian paha',
      '5 lbr jamur kuping (rendam smpe lembut)',
      '4 butir bawang merah',
      '2 siung bawang putih',
      '2 cm jahe',
      '2 sdm kecap manis',
      '1 sdm saos tiram',
      '1 sdt kecap ikan',
      '1 sdt minyak wijen',
      '1 sdm kaldu bubuk',
      '400 ml air',
      'Secukupnya minyak goreng untuk menumis',
    ],
    howToMake: [
      '1. Tumis bawang putih dan bawang merah hingga harum. Kemudian tambahkan cabai merah dan tomat. Tumis hingga semua bahan tercampur rata.',
      '2. Tambahkan fillet paha ayam dan jamur kuping ke dalam tumisan bumbu. Masak hingga ayam dan jamur matang.',
      '3. Tambahkan kecap manis ke dalam masakan dan aduk rata. Masak hingga semua bahan tercampur rata dan bumbu meresap.',
      '4. Sajikan: Ayam Jamur Kuping siap disajikan.',
    ],
  ),
  Receipt(
    name: 'Grilled chicken steak with mushroom sauce',
    description:
        'Grilled Chicken Steak with Mushroom Sauce adalah hidangan yang terdiri dari fillet dada ayam yang dipanggang dan disajikan dengan saus jamur',
    imageAsset: 'images/grilled_chicken_steak_with_mushroom_sauce.jpg',
    ingredients: [
      '2 pasang dada ayam suhu ruang',
      'secukupnya Garam',
      'secukupnya Merica',
      'secukupnya Thyme',
      '100 gr jamur champignon, iris-iris',
      '1 sdm butter',
      '200 ml susu cair',
      '1 sdt garam',
      '1/2 sdt lada',
      '1 sdt kaldu jamur',
      'secukupnya Oregano',
      '1 sdm maizena dilarutkan dengan sedikit air',
      'Buncis, rebus',
      'Kentang goreng',
      'secukupnya Butter',
      '2 siung bawang putih geprek',
    ],
    howToMake: [
      '1. Untuk marinasi ayam, lumuri garam, merica, dan thyme ke seluruh permukaan ayam bolak balik. Diamkan minimal 1 jam',
      '2. Panaskan wajan, masukkan olive oil. Panggang ayam, ketika dibalik tambahkan butter dan bawang putih geprek, siram-siram ke ayam.',
      '3. Membuat mushroom sauce. Tumis jamur diatas wajan hingga kecokelatan dan mengeluarkan air, lalu masukkan butter, aduk hingga rata. Tambahkan susu cair, oregano, garam, lada, dan kaldu jamur. Setelah tercampur rata, masukkan larutan tepung maizena. Masak hingga mengental',
      '4. Sajikan dengan kentang goreng/mashed potato dan buncis/sayuran lainnya',
    ],
  ),
  Receipt(
    name: 'Dimsum Ayam Jamur',
    description:
        'Dimsum Ayam Jamur Merang adalah hidangan ayam dan jamur merang yang dibungkus dengan kulit dimsum dan dikukus.',
    imageAsset: 'images/dimsum_ayam_jamur.jpg',
    ingredients: [
      '300 gr ayam fillet paha',
      '100 gr jamur merang (cacah kasar)',
      '1 wortel (parut halus)',
      '1 daun bawang (iris tipis)',
      '3 bawang putih (cacah halus)',
      '1 putih telur',
      '3 sdm tapioka',
      '1 sdm saus tiram',
      '1 sdm kecap asin',
      '1/2 sdm minyak wijen',
      '1/2 sdt garam',
      'Secukupnya merica dan kaldu',
      'Kulit dimsum',
    ],
    howToMake: [
      '1. Blender ayam dengan sedikit air dingin, sisihkan. Saya pribadi suka adonan ayam yang gak terlalu halus, supaya pas dimakan jadi terasa juicy dan potongan ayamnya masih terasa 😍 Sila disesuaikan ya.',
      '2. Tumis bawang putih hingga harum, masukkan jamur yang telah dicacah dan oseng oseng sebentar hingga matang.',
      '3. Campur ayam yang telah diblender dengan jamur dan bumbu-bumbu, aduk rata.',
      '4. Ambil satu sendok makan adonan, taruh di atas kulit dimsum lalu lipat pinggirnya. Beri topping parutan wortel/potongan jamur.',
      '5. Taruh di kukusan yang telah dipanaskan dan dioles minyak, lalu kukus selama kurang lebih 25 menit atau hingga matang.',
      '6. Sajikan dimsum dengan mayo dan saus atau chili oil 😋',
    ],
  ),
];
